version: '3.8'
services:
  whisper:
    build: ./whisper-api
    environment:
      - WHISPER_LANGUAGE=de
    restart: unless-stopped

  webserver:
    build: ./nginx
    ports:
      - "8077:8077"
    depends_on:
      - whisper
    restart: unless-stopped