version: '3.8'
services:
  whisper:  
    build:
      context: ./whisper-api
      dockerfile: Dockerfile-Deploy
    restart: unless-stopped

  webserver:
    build: ./nginx
    ports:
      - "8077:8077"
    depends_on:
      - whisper
    restart: unless-stopped